-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 18:31:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wordgen
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wordgen` ;

-- -----------------------------------------------------
-- Schema wordgen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordgen` DEFAULT CHARACTER SET utf8 ;
USE `wordgen` ;

-- -----------------------------------------------------
-- Table `wordgen`.`tbl_rawfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgen`.`tbl_rawfile` ;

CREATE TABLE IF NOT EXISTS `wordgen`.`tbl_rawfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `post` VARCHAR(255) NULL,
  `survey` VARCHAR(255) NULL,
  `purchase_ranges` JSON NULL,
  `period` VARCHAR(255) NULL,
  `service` JSON NULL,
  `manpower` VARCHAR(255) NULL,
  `achievement` VARCHAR(255) NULL,
  `acceptance` VARCHAR(255) NULL,
  `payment` VARCHAR(255) NULL,
  `ownership` VARCHAR(255) NULL,
  `other` JSON NULL,
  `attachment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgen`.`tbl_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgen`.`tbl_file` ;

CREATE TABLE IF NOT EXISTS `wordgen`.`tbl_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `understanding` VARCHAR(1023) NULL,
  `schedule` VARCHAR(1023) NULL,
  `quality` VARCHAR(1023) NULL,
  `commitment` VARCHAR(1023) NULL,
  `back` VARCHAR(1023) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgen`.`file_rawfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgen`.`file_rawfile` ;

CREATE TABLE IF NOT EXISTS `wordgen`.`file_rawfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_id` INT NULL,
  `rawfile_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgen`.`tbl_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgen`.`tbl_history` ;

CREATE TABLE IF NOT EXISTS `wordgen`.`tbl_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rawfile_id` INT NULL,
  `history` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
